version: '3.8'

services:
# Postgres DB Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

# Django Server Service
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: